### PR TITLE
add a new constructor to CompressedColumnStorage and remove cloning from PermuteColumns

### PR DESCRIPTION
**Pull request by bigworld12**

### CODE REVIEW

**Comment by wo80** [comment]
In fact, cloning is needed:
```c#
int rows = 2;
int columns = 2;

var C = Converter.FromColumnMajorArray(new double[] { 1.0, 2.0, 3.0, 4.0 }, rows, columns);
var A = Converter.ToCompressedColumnStorage(C);
var Ap = A.Clone();

var actualColumn = new double[rows];
var expectedColumn = new double[rows];

var p = Permutation.Create(columns, -1);

Ap.PermuteColumns(p);

for (int i = 0; i < columns; i++)
{
    A.Column(p[i], expectedColumn);
    Ap.Column(i, actualColumn);

    // This will fail without cloning!
    CollectionAssert.AreEqual(expectedColumn, actualColumn);
}
```

**Comment by bigworld12** [comment]
oh sorry i didn't notice the other 3 parameters were the outputs, cloning is still not needed, just 3 empty arrays would work

**Comment by wo80** [comment]
Maybe the PermuteColumns method should return a new CompressedColumnStorage instance? This would make clear, that new memory will be allocated.

**Comment by bigworld12** [comment]
then i suggest making the class CompressedColumnStorage<T> non-abstract for it to have a constructor

**Comment by wo80** [comment]
This would imply a lot of refactoring. You could use `CompressedColumnStorage<T>.Create(...)` for now. I'm not quite happy with this solution, but I also don't think, that the user should be able to create `CompressedColumnStorage<T>` objects.

**Comment by bigworld12** [comment]
then i think this should be good

**Pull request merged**
